export const errorName = Object.freeze({
  BENTO_BACKEND_NOT_CONNECTED: "BENTO_BACKEND_NOT_CONNECTED",
  IDC_INTERNAL_SERVER_ERROR: "IDC_INTERNAL_SERVER_ERROR",
  TCIA_INTERNAL_SERVER_ERROR: "TCIA_INTERNAL_SERVER_ERROR",
});
